#!/bin/bash

# Code generated by Deepseek AI

BASE_FILE="install.sh"
MODULES_DIR="modules"

# Check if files/directories exist
if [ ! -d "$MODULES_DIR" ]; then
    echo "Error: $MODULES_DIR directory not found!"
    exit 1
fi

# Add header
echo "# Comment the lines of modules you don't wish to install" > "$BASE_FILE"
{
    echo ""
    echo "# Auto-generated module imports - $(date)" 
} >> "$BASE_FILE"

# Process files by directory structure
current_dir=""
find "$MODULES_DIR" -type f -name "*.sh" | awk -F'/' '{print NF, $0}' | sort -n | cut -d' ' -f2- | while read -r file; do
    dir_name=$(dirname "$file")
    
    # If we're in a new directory, add a section header
    if [ "$dir_name" != "$current_dir" ]; then
        current_dir="$dir_name"
        {
            echo "" >> "$BASE_FILE"
            echo "# $(echo $current_dir | sed 's|^|./|')" 
        } >> "$BASE_FILE"
    fi
    
    echo "source \"./$file\"" >> "$BASE_FILE"
done

echo "base.sh has been created with the module paths!"
