paths = ["/path/to/override"] # path dependency overrides

[alias]     # command aliases
b = "build"
c = "check"
t = "test"
[net]
git-fetch-with-cli = true   # use the `git` executable for git operations
